name: Build on Oracle Test Pilot

on:
  push:
    branches:
      #TODO
      #- 'main'
      #- '[0-9].[0-9].x'
      - 'otp-integration'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  build-all-otp:
    permissions:
      contents: read
    name: Build Oracle AI Vector Store module
    #TODO
    #if: ${{ github.repository_owner == 'spring-projects' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - rdbms: base-database-service-26ai
          - rdbms: autonomous-transaction-processing-serverless-26ai
    runs-on: [ self-hosted, Linux, X64, OracleTestPilot ]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#          cache: 'maven'
      - name: Set up JDK
        uses: graalvm/setup-graalvm@aafbedb8d382ed0ca6167d3a051415f20c859274 # v1.2.8
        with:
          distribution: 'graalvm'
          java-version: '25'

      - name: Setup Maven Build-Cache (~/.m2/build-cache)
        if: ${{ github.event_name != 'schedule' }}
        uses: actions/cache@v4
        with:
          path: ~/.m2/build-cache
          # See pr-check.yml for an explanation of the key format
          key: build-cache-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}-${{ github.run_id }}
          restore-keys: |
            build-cache-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}-
            build-cache-${{ runner.os }}-

      - id: create_database
        uses: oracle-actions/setup-testpilot@896b7a475b58579357f7ad034ff43de53cde4c19 # v1.0.22
        with:
          oci-service: ${{ matrix.rdbms }}
          action: create
          user: spring_ai

      - name: Build all modules with unit tests
        env:
          RDBMS: ${{ matrix.rdbms }}
          RUNID: ${{ github.run_number }}
          TESTPILOT_CONNECTION_STRING_SUFFIX: ${{ steps.create_database.outputs.connection_string_suffix }}
          TESTPILOT_PASSWORD: ${{ steps.create_database.outputs.database_password }}
          TESTPILOT_USERNAME: spring_ai_${{ github.run_number }}
          API_HOST: ""
          TESTPILOT_CLIENT_ID: ""
          TESTPILOT_TOKEN: ""
          TESTCONTAINERS_DISABLED: true
          TESTCONTAINERS_RYUK_DISABLED: true
          # Needed for TFO (TCP fast open)
          LD_PRELOAD: /home/ubuntu/libtfojdbc1.so
          LD_LIBRARY_PATH: /home/ubuntu
        run: |
          ./mvnw --batch-mode -ntp --update-snapshots clean install -pl 'vector-stores/spring-ai-oracle-store'

#TODO
#      - id: delete_database
#        uses: oracle-actions/setup-testpilot@896b7a475b58579357f7ad034ff43de53cde4c19 # v1.0.22
#        if: always()
#        with:
#          oci-service: ${{ matrix.rdbms }}
#          action: delete
#          user: spring_ai
